name: graphnet
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cartopy=0.21
  - dask=2023.1
  - dask-core=2023.1
  - einops=0.6
  - geos=3.8
  - h3-py=3.7
  - ipython=8.10
  - jupyter_core=5.2
  - matplotlib=3.6
  - mkl=2021.4
  - numpy=1.21
  - pandas=1.5
  - pip=22.3
  - proj=8.2
  - python=3.8
  - scikit-image=0.19
  - scikit-learn=1.2
  - scipy=1.10
  - shapely=1.8
  - tqdm=4.64
  - wheel=0.38
  - xarray=2022.11

# plus install torch 1.8.1 somewhere else, 
# plus install with pip to base:
## pip install netCDF4
## pip install h5netcdf
## pip install torch_geometric
## pip install einops
## pip install torch-scatter
